name: 'Action debootstrap'
description: 'Run cross-architecture via debootstrap.'
author: 'dabao1955'
inputs:
  arch:
    default: 'arm64'
  version:
    default: 'bookworm'  


runs:
  using: 'composite'
  steps:

    - name: Build Kernel
      shell: bash
      run: |

         if [[ ${GITHUB_ACTIONS} != "true" || ${OSTYPE} != "linux-gnu" || ! -f /bin/apt ]]; then
             printf "This Action Is Intended For Debian-based Runner.\n"
             exit 127
         fi

         if [ "$(id -u)" -eq 0 ]; then
             export SU=
         else
             export SU=sudo
         fi
         echo "::group:: Installing Building Depend Packages"
         "$SU" apt-get update
         "$SU" apt-get install --no-install-recommends -y qemu-user-static debootstrap
         echo "::endgroup::"

         echo "::group:: Initializing rootfs"
         "$SU" debootstrap  --variant=minbase --arch ${{ inputs.arch }} ${{ inputs.version }} "$HOME/rootfs"
         echo "::endgroup::"

         echo "::group:: Downloading shell"
         "$SU" wget https://github.com/NekoSekaiMoe/debchroot/raw/main/debsh -O /usr/bin/debsh
         "$SU" chmod +x -v /usr/bin/debsh
         echo "::endgroup::"

         echo "::group:: Running uname -a"
         /usr/bin/debsh uname -a
         echo "::endgroup::"
